AWSTemplateFormatVersion: 2010-09-09
Description: AWS CloudFormation template to create CloudTrail and S3 bucket.
Parameters:
  TrailName:
    Type: String
  BucketName:
    Type: String

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  MyS3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CloudTrailBucketPolicy
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:GetBucketAcl"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyS3Bucket]]
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
          - Sid: CloudTrailBucketPolicyPut
            Effect: Allow
            Principal:
              Service: "cloudtrail.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Join ['', ['arn:aws:s3:::', !Ref MyS3Bucket, '/*']]
            Condition:
              StringEquals:
                "AWS:SourceArn": !Sub "arn:aws:cloudtrail:${AWS::Region}:${AWS::AccountId}:trail/${TrailName}"
                "s3:x-amz-acl": "bucket-owner-full-control"

  MyCloudTrail:
    Type: AWS::CloudTrail::Trail
    Properties:
      S3BucketName: !Ref MyS3Bucket
      IsLogging: true
      TrailName: !Ref TrailName
      EnableLogFileValidation: true
      IncludeGlobalServiceEvents: true
      IsMultiRegionTrail: true
      
Outputs:
  ARN:
    Description: The trail ARN
    Value:
      'Fn::GetAtt':
        - MyCloudTrail
        - Arn
